### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by limsocheat** [Tofandel/inertia-vue3-modal#1]
cannot install 

`npm i vendor/tofandel/inertia-vue-modal`

**Comment by Tofandel** [comment]
Did you install the composer package first, or made sure there where no errors during installation?

**Comment by limsocheat** [comment]
Hi @Tofandel,

Yes now I can install, but I have another problem when trying to import to layout.
I am using Inertia Vue 3 with vite. 

`import { InertiaModal, ModalSlot } from "@tofandel/inertia-vue-modal";`

```
Failed to resolve entry for package "@tofandel/inertia-vue-modal". The package may have incorrect main/module/exports specified in its package.json.
6:58:41 PM [vite] Internal server error: Failed to resolve entry for package "@tofandel/inertia-vue-modal". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/limsocheat/Developments/Sakal/sakal/resources/js/Layouts/DashboardLayout.vue
      at packageEntryFailure (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34410:11)
      at resolvePackageEntry (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34407:5)
      at tryNodeResolve (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34161:20)
      at Context.resolveId (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:33963:28)
      at async Object.resolveId (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:35216:32)
      at async TransformContext.resolve (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:34981:23)
      at async normalizeUrl (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:40175:34)
      at async TransformContext.transform (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:40315:47)
      at async Object.transform (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:35284:30)
      at async loadAndTransform (file:///Users/limsocheat/Developments/Sakal/sakal/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:39812:29)
```

**Comment by Tofandel** [comment]
Ah yes the composer package doesn't contain the build

I just pushed it, try updating the composer package and try again

**Comment by limsocheat** [comment]
Hi @Tofandel, it works perfectly now. 

But I have another problem with closing modal. For example: 

- I want modal to be persistence, so I will need to have one button to handle closing dialog event 
- After I submitted the form, it already stored in database, however, I want to close the modal, but I don't know where to handle modal closing. 

Thanks in advance.

**Comment by limsocheat** [comment]
Another issue I have is: 

```
[Vue warn]: Extraneous non-props attributes (is-modal, errors, flash, menu) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ModalableWrapper is-modal="" errors= {} flash= {message: null}  ... > 
  at <Create is-modal="" errors= {} flash= {message: null}  ... > 
  at <InertiaModal> 
  at <VApp> 
  at <DashboardLayout errors= {} flash= {message: null} menu= (5) [{…}, {…}, {…}, {…}, {…}]  ... > 
  at <Inertia initialPage= {component: 'Library::Dashboard/Inertia/V3/Books/Index', props: {…}, url: '/km/dashboard/library/books?page=1', version: '', scrollRegions: Array(0), …} initialComponent= {__name: 'Index', props: {…}, __hmrId: '08dbd941', setup: ƒ, render: ƒ, …} resolveComponent=fn<h2>  ... > 
  at <App>
```

**Comment by Tofandel** [comment]
Without seeing your template it will be hard to help you

The warning is because you're passing props to a component without props, multiple roots and forgot the `inheritAtts: false`

To close the modal there is either the slot prop `close` as in the example or in a ModalableWrapper you can use 
```
<template #modal="{close}">
```

**Comment by limsocheat** [comment]
Hi @Tofandel, Thanks you, now I can close dialog from my form component inside `<template> `tag.

But I don't know how to close dialog from script tag, let say use click submit button to submit form database via submit function inside `<script setup>` tag. 

```
<script setup>
const submit = () => {
        item.post(route("dashboard.library.books.store"), {
            **onSuccess: () => /// want to close dialog here,**
        });
    };
</script>
```

Also how can we close dialog from the parent component, let say I am in the `index.vue` component, when click $inertia.visitInModal, I want to handle close dialog inside `<script setup>` tag. 

My `index.vue` function to open `create.vue `component dialog. 

```
const createItem = () => {
        Inertia.visitInModal(route("dashboard.library.books.create"), {
            redirectBack: (evt) => {
                `// evt.close(); How can I close dialog after the controller redirection `
            },
        });
    };
```

Sorry if I ask too many questions, because I really want to implement this Visit in Modal feature on my project. 

Regard.

**Comment by Royalerror** [comment]
Hello I have a problem on the installation.

I'm using  Laravel v9.35.1 plugin v0.6.1 with Vite 3.0.0

`import { InertiaModal, ModalSlot } from "@tofandel/inertia-vue-modal";`

```
The requested module '/vendor/tofandel/inertia-vue-modal/dist/inertia-vue-modal.umd.min.js' does not provide an export named 'InertiaModal'
```

**Comment by Tofandel** [comment]
It definitely has those exports, make sure you're using an up to date version (latest is 0.2.26)

**Comment by Royalerror** [comment]
Fixed it by removing `"@tofandel/inertia-vue-modal": "file:vendor/tofandel/inertia-vue-modal",` from package.json and by reinstalling it with `npm i @tofandel/inertia-vue-modal`
